[build]
  publish = "public"   
  functions = "netlify/functions"  # Path to your functions folder

[[redirects]]
  from = "/send-email"
  to = "/.netlify/functions/send-email"
  status = 200
  force = true
